package com.chebo16.metroit;

import com.chebo16.metroit.dao.EquipmentDAO;
import com.chebo16.metroit.exception.NotFoundException;
import com.chebo16.metroit.exception.ValidationException;
import com.chebo16.metroit.model.Equipment;
import com.chebo16.metroit.model.enums.EquipmentStatus;
import com.chebo16.metroit.service.EquipmentService;

import java.sql.SQLException;
import java.util.List;

public class EquipmentServiceTest {

    public static void main(String[] args) {

        EquipmentService equipmentService =
                new EquipmentService();

        EquipmentDAO equipmentDAO =
                new EquipmentDAO();

        Long createdEquipmentId = null;
        boolean cleanupCompleted = false;

        try {
            System.out.println(
                    "Testing EquipmentService operations..."
            );

            System.out.println();

            // 1. READ ALL

            List<Equipment> equipmentBeforeCreate =
                    equipmentService.getAllEquipment();

            int countBeforeCreate =
                    equipmentBeforeCreate.size();

            System.out.println(
                    "1. getAllEquipment() completed successfully."
            );

            System.out.println(
                    "Equipment records before create: "
                            + countBeforeCreate
            );

            System.out.println();

            // 2. CREATE AND NORMALIZE VALUES

            String uniqueSuffix =
                    String.valueOf(
                            System.currentTimeMillis()
                    );

            String inventoryNumber =
                    "SERVICE-TEST-" + uniqueSuffix;

            String serialNumber =
                    "SERVICE-SERIAL-" + uniqueSuffix;

            Equipment newEquipment = new Equipment(
                    "  " + inventoryNumber + "  ",
                    "  Temporary Service Test Device  ",
                    "  Test device  ",
                    "  Test Manufacturer  ",
                    "  Test Model  ",
                    "  " + serialNumber + "  ",
                    "  192.0.2.210  ",
                    "  Temporary equipment created "
                            + "by EquipmentServiceTest.  "
            );

            Equipment createdEquipment =
                    equipmentService.createEquipment(
                            newEquipment
                    );

            createdEquipmentId =
                    createdEquipment.getId();

            if (createdEquipmentId == null
                    || createdEquipmentId <= 0) {

                throw new IllegalStateException(
                        "Generated equipment ID is invalid."
                );
            }

            requireCondition(
                    inventoryNumber.equals(
                            createdEquipment
                                    .getInventoryNumber()
                    ),
                    "Inventory number was not normalized."
            );

            requireCondition(
                    "Temporary Service Test Device".equals(
                            createdEquipment.getName()
                    ),
                    "Equipment name was not normalized."
            );

            requireCondition(
                    "Test device".equals(
                            createdEquipment.getType()
                    ),
                    "Equipment type was not normalized."
            );

            requireCondition(
                    "Test Manufacturer".equals(
                            createdEquipment.getManufacturer()
                    ),
                    "Manufacturer was not normalized."
            );

            requireCondition(
                    "Test Model".equals(
                            createdEquipment.getModel()
                    ),
                    "Model was not normalized."
            );

            requireCondition(
                    serialNumber.equals(
                            createdEquipment.getSerialNumber()
                    ),
                    "Serial number was not normalized."
            );

            requireCondition(
                    "192.0.2.210".equals(
                            createdEquipment.getIpAddress()
                    ),
                    "IP address was not normalized."
            );

            requireCondition(
                    createdEquipment.getStatus()
                            == EquipmentStatus.ACTIVE,
                    "New equipment must have ACTIVE status."
            );

            requireCondition(
                    createdEquipment.getCreatedAt() != null,
                    "createdAt was not generated by MySQL."
            );

            System.out.println(
                    "2. createEquipment() completed successfully."
            );

            System.out.println(
                    "Generated equipment ID: "
                            + createdEquipmentId
            );

            System.out.println(
                    "Default status: "
                            + createdEquipment.getStatus()
            );

            System.out.println(
                    "Created at: "
                            + createdEquipment.getCreatedAt()
            );

            System.out.println();

            // 3. READ BY ID

            Equipment loadedEquipment =
                    equipmentService.getEquipmentById(
                            createdEquipmentId
                    );

            requireCondition(
                    createdEquipmentId.equals(
                            loadedEquipment.getId()
                    ),
                    "getEquipmentById() returned "
                            + "unexpected equipment."
            );

            System.out.println(
                    "3. getEquipmentById() "
                            + "completed successfully."
            );

            System.out.println("Loaded equipment:");
            System.out.println(loadedEquipment);

            System.out.println();

            // 4. UPDATE

            loadedEquipment.setName(
                    "  Updated Service Test Device  "
            );

            loadedEquipment.setManufacturer(
                    "  Updated Manufacturer  "
            );

            loadedEquipment.setModel(
                    "  Updated Model  "
            );

            loadedEquipment.setNotes(
                    "  Equipment was updated "
                            + "by EquipmentServiceTest.  "
            );

            Equipment updatedEquipment =
                    equipmentService.updateEquipment(
                            loadedEquipment
                    );

            requireCondition(
                    "Updated Service Test Device".equals(
                            updatedEquipment.getName()
                    ),
                    "Equipment name was not updated."
            );

            requireCondition(
                    "Updated Manufacturer".equals(
                            updatedEquipment.getManufacturer()
                    ),
                    "Manufacturer was not updated."
            );

            requireCondition(
                    "Updated Model".equals(
                            updatedEquipment.getModel()
                    ),
                    "Model was not updated."
            );

            System.out.println(
                    "4. updateEquipment() "
                            + "completed successfully."
            );

            System.out.println("Updated equipment:");
            System.out.println(updatedEquipment);

            System.out.println();

            // 5. CHANGE STATUS

            Equipment inactiveEquipment =
                    equipmentService.changeStatus(
                            createdEquipmentId,
                            EquipmentStatus.INACTIVE
                    );

            requireCondition(
                    inactiveEquipment.getStatus()
                            == EquipmentStatus.INACTIVE,
                    "Equipment status was not changed "
                            + "to INACTIVE."
            );

            System.out.println(
                    "5. changeStatus(INACTIVE) "
                            + "completed successfully."
            );

            System.out.println(
                    "Equipment status: "
                            + inactiveEquipment.getStatus()
            );

            System.out.println();

            // 6. DECOMMISSION

            Equipment decommissionedEquipment =
                    equipmentService
                            .decommissionEquipment(
                                    createdEquipmentId
                            );

            requireCondition(
                    decommissionedEquipment.getStatus()
                            == EquipmentStatus.DECOMMISSIONED,
                    "Equipment was not decommissioned."
            );

            System.out.println(
                    "6. decommissionEquipment() "
                            + "completed successfully."
            );

            System.out.println(
                    "Equipment status: "
                            + decommissionedEquipment.getStatus()
            );

            System.out.println();

            // 7. DUPLICATE INVENTORY NUMBER VALIDATION

            Equipment duplicateInventoryEquipment =
                    new Equipment(
                            inventoryNumber,
                            "Duplicate Inventory Device",
                            "Test device",
                            "Test Manufacturer",
                            "Test Model",
                            "UNIQUE-SERIAL-" + uniqueSuffix,
                            null,
                            "Duplicate inventory validation test."
                    );

            expectValidationException(
                    () -> equipmentService.createEquipment(
                            duplicateInventoryEquipment
                    ),
                    "Duplicate inventory number "
                            + "was not rejected."
            );

            System.out.println(
                    "7. Duplicate inventory number "
                            + "was rejected successfully."
            );

            System.out.println();

            // 8. DUPLICATE SERIAL NUMBER VALIDATION

            Equipment duplicateSerialEquipment =
                    new Equipment(
                            "UNIQUE-INVENTORY-" + uniqueSuffix,
                            "Duplicate Serial Device",
                            "Test device",
                            "Test Manufacturer",
                            "Test Model",
                            serialNumber,
                            null,
                            "Duplicate serial validation test."
                    );

            expectValidationException(
                    () -> equipmentService.createEquipment(
                            duplicateSerialEquipment
                    ),
                    "Duplicate serial number "
                            + "was not rejected."
            );

            System.out.println(
                    "8. Duplicate serial number "
                            + "was rejected successfully."
            );

            System.out.println();

            // 9. INVALID ID VALIDATION

            expectValidationException(
                    () -> equipmentService
                            .getEquipmentById(0),
                    "Invalid equipment ID "
                            + "was not rejected."
            );

            System.out.println(
                    "9. Invalid equipment ID "
                            + "was rejected successfully."
            );

            System.out.println();

            // 10. NOT FOUND VALIDATION

            expectNotFoundException(
                    () -> equipmentService
                            .getEquipmentById(
                                    Long.MAX_VALUE
                            ),
                    "Missing equipment did not produce "
                            + "NotFoundException."
            );

            System.out.println(
                    "10. Missing equipment produced "
                            + "NotFoundException successfully."
            );

            System.out.println();

            // 11. CLEANUP

            cleanupCompleted =
                    equipmentDAO.delete(
                            createdEquipmentId
                    );

            requireCondition(
                    cleanupCompleted,
                    "Temporary equipment cleanup "
                            + "returned false."
            );

            /*
             * A final local variable is required because
             * createdEquipmentId is modified earlier and therefore
             * cannot be captured directly by a lambda expression.
             */
            final long deletedEquipmentId =
                    createdEquipmentId;

            expectNotFoundException(
                    () -> equipmentService
                            .getEquipmentById(
                                    deletedEquipmentId
                            ),
                    "Equipment still exists after cleanup."
            );

            System.out.println(
                    "11. Temporary equipment "
                            + "was deleted successfully."
            );

            System.out.println(
                    "Deleted equipment ID: "
                            + deletedEquipmentId
            );

            System.out.println();

            // 12. FINAL COUNT CHECK

            int countAfterCleanup =
                    equipmentService
                            .getAllEquipment()
                            .size();

            requireCondition(
                    countAfterCleanup
                            == countBeforeCreate,
                    "Equipment count changed after the test. "
                            + "Before: "
                            + countBeforeCreate
                            + ", after: "
                            + countAfterCleanup
            );

            System.out.println(
                    "Equipment records after cleanup: "
                            + countAfterCleanup
            );

            System.out.println();

            System.out.println(
                    "All EquipmentService operations "
                            + "completed successfully."
            );

        } catch (SQLException exception) {

            System.err.println(
                    "EquipmentService cleanup SQL error."
            );

            System.err.println(
                    "SQL error code: "
                            + exception.getErrorCode()
            );

            System.err.println(
                    "SQL state: "
                            + exception.getSQLState()
            );

            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

        } catch (RuntimeException exception) {

            System.err.println(
                    "EquipmentService test failed."
            );

            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

            exception.printStackTrace();

        } finally {

            if (createdEquipmentId != null
                    && !cleanupCompleted) {

                try {
                    boolean removed =
                            equipmentDAO.delete(
                                    createdEquipmentId
                            );

                    if (removed) {
                        System.out.println();

                        System.out.println(
                                "Temporary equipment was "
                                        + "removed during "
                                        + "automatic cleanup."
                        );
                    }

                } catch (SQLException cleanupException) {

                    System.err.println();

                    System.err.println(
                            "Automatic equipment cleanup failed."
                    );

                    System.err.println(
                            "Temporary equipment ID: "
                                    + createdEquipmentId
                    );

                    System.err.println(
                            "Reason: "
                                    + cleanupException.getMessage()
                    );
                }
            }
        }
    }

    private static void expectValidationException(
            Runnable operation,
            String failureMessage
    ) {

        try {
            operation.run();

        } catch (ValidationException exception) {
            return;
        }

        throw new IllegalStateException(
                failureMessage
        );
    }

    private static void expectNotFoundException(
            Runnable operation,
            String failureMessage
    ) {

        try {
            operation.run();

        } catch (NotFoundException exception) {
            return;
        }

        throw new IllegalStateException(
                failureMessage
        );
    }

    private static void requireCondition(
            boolean condition,
            String message
    ) {

        if (!condition) {
            throw new IllegalStateException(
                    message
            );
        }
    }
}