package com.chebo16.metroit;

import com.chebo16.metroit.exception.NotFoundException;
import com.chebo16.metroit.exception.ValidationException;
import com.chebo16.metroit.model.User;
import com.chebo16.metroit.model.enums.UserRole;
import com.chebo16.metroit.service.UserService;
import com.chebo16.metroit.util.DatabaseConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class UserServiceTest {

    private static final String DELETE_TEST_USER_SQL = """
            DELETE FROM users
            WHERE id = ?
            """;

    public static void main(String[] args) {

        UserService userService =
                new UserService();

        Long createdUserId = null;
        boolean cleanupCompleted = false;

        try {
            System.out.println(
                    "Testing UserService operations..."
            );

            System.out.println();

            // 1. READ ALL

            List<User> usersBeforeCreate =
                    userService.getAllUsers();

            int countBeforeCreate =
                    usersBeforeCreate.size();

            System.out.println(
                    "1. getAllUsers() completed successfully."
            );

            System.out.println(
                    "Users before create: "
                            + countBeforeCreate
            );

            System.out.println();

            // 2. CREATE AND NORMALIZE

            String uniqueSuffix =
                    String.valueOf(
                            System.currentTimeMillis()
                    );

            String originalUsername =
                    "service_test_" + uniqueSuffix;

            String originalEmail =
                    "service_test_"
                            + uniqueSuffix
                            + "@example.com";

            User newUser = new User(
                    "  " + originalUsername + "  ",
                    "  TEMPORARY_SERVICE_TEST_HASH  ",
                    "  Temporary Service Test User  ",
                    "  " + originalEmail + "  ",
                    UserRole.TECHNICIAN
            );

            User createdUser =
                    userService.createUser(newUser);

            createdUserId =
                    createdUser.getId();

            if (createdUserId == null
                    || createdUserId <= 0) {

                throw new IllegalStateException(
                        "Generated user ID is invalid."
                );
            }

            requireCondition(
                    originalUsername.equals(
                            createdUser.getUsername()
                    ),
                    "Username was not normalized."
            );

            requireCondition(
                    "TEMPORARY_SERVICE_TEST_HASH".equals(
                            createdUser.getPasswordHash()
                    ),
                    "Password hash was not normalized."
            );

            requireCondition(
                    "Temporary Service Test User".equals(
                            createdUser.getFullName()
                    ),
                    "Full name was not normalized."
            );

            requireCondition(
                    originalEmail.equals(
                            createdUser.getEmail()
                    ),
                    "Email was not normalized."
            );

            requireCondition(
                    createdUser.getRole()
                            == UserRole.TECHNICIAN,
                    "User role is incorrect."
            );

            requireCondition(
                    createdUser.isActive(),
                    "New user must be active."
            );

            requireCondition(
                    createdUser.getCreatedAt() != null,
                    "createdAt was not generated by MySQL."
            );

            System.out.println(
                    "2. createUser() completed successfully."
            );

            System.out.println(
                    "Generated user ID: "
                            + createdUserId
            );

            System.out.println(
                    "User active status: "
                            + createdUser.isActive()
            );

            System.out.println();

            // 3. READ BY ID

            User loadedUser =
                    userService.getUserById(
                            createdUserId
                    );

            requireCondition(
                    createdUserId.equals(
                            loadedUser.getId()
                    ),
                    "getUserById() returned "
                            + "an unexpected user."
            );

            System.out.println(
                    "3. getUserById() "
                            + "completed successfully."
            );

            System.out.println("Loaded user:");
            System.out.println(loadedUser);

            System.out.println();

            // 4. READ BY USERNAME

            User userByUsername =
                    userService.getUserByUsername(
                            "  " + originalUsername + "  "
                    );

            requireCondition(
                    createdUserId.equals(
                            userByUsername.getId()
                    ),
                    "getUserByUsername() returned "
                            + "an unexpected user."
            );

            System.out.println(
                    "4. getUserByUsername() "
                            + "completed successfully."
            );

            System.out.println(
                    "Found username: "
                            + userByUsername.getUsername()
            );

            System.out.println();

            // 5. UPDATE

            String updatedUsername =
                    "service_updated_" + uniqueSuffix;

            String updatedEmail =
                    "service_updated_"
                            + uniqueSuffix
                            + "@example.com";

            loadedUser.setUsername(
                    "  " + updatedUsername + "  "
            );

            loadedUser.setPasswordHash(
                    "  UPDATED_SERVICE_TEST_HASH  "
            );

            loadedUser.setFullName(
                    "  Updated Service Test User  "
            );

            loadedUser.setEmail(
                    "  " + updatedEmail + "  "
            );

            loadedUser.setRole(
                    UserRole.ADMIN
            );

            User updatedUser =
                    userService.updateUser(
                            loadedUser
                    );

            requireCondition(
                    updatedUsername.equals(
                            updatedUser.getUsername()
                    ),
                    "Username was not updated."
            );

            requireCondition(
                    "UPDATED_SERVICE_TEST_HASH".equals(
                            updatedUser.getPasswordHash()
                    ),
                    "Password hash was not updated."
            );

            requireCondition(
                    "Updated Service Test User".equals(
                            updatedUser.getFullName()
                    ),
                    "Full name was not updated."
            );

            requireCondition(
                    updatedEmail.equals(
                            updatedUser.getEmail()
                    ),
                    "Email was not updated."
            );

            requireCondition(
                    updatedUser.getRole()
                            == UserRole.ADMIN,
                    "User role was not updated."
            );

            System.out.println(
                    "5. updateUser() completed successfully."
            );

            System.out.println("Updated user:");
            System.out.println(updatedUser);

            System.out.println();

            // 6. DEACTIVATE

            User inactiveUser =
                    userService.deactivateUser(
                            createdUserId
                    );

            requireCondition(
                    !inactiveUser.isActive(),
                    "User was not deactivated."
            );

            System.out.println(
                    "6. deactivateUser() "
                            + "completed successfully."
            );

            System.out.println(
                    "User active status: "
                            + inactiveUser.isActive()
            );

            System.out.println();

            // 7. ACTIVATE

            User activeUser =
                    userService.activateUser(
                            createdUserId
                    );

            requireCondition(
                    activeUser.isActive(),
                    "User was not activated."
            );

            System.out.println(
                    "7. activateUser() "
                            + "completed successfully."
            );

            System.out.println(
                    "User active status: "
                            + activeUser.isActive()
            );

            System.out.println();

            // 8. DUPLICATE USERNAME

            User duplicateUsernameUser = new User(
                    updatedUsername,
                    "DUPLICATE_USERNAME_HASH",
                    "Duplicate Username User",
                    "unique_"
                            + uniqueSuffix
                            + "@example.com",
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            duplicateUsernameUser
                    ),
                    "Duplicate username was not rejected."
            );

            System.out.println(
                    "8. Duplicate username "
                            + "was rejected successfully."
            );

            System.out.println();

            // 9. DUPLICATE EMAIL

            User duplicateEmailUser = new User(
                    "unique_user_" + uniqueSuffix,
                    "DUPLICATE_EMAIL_HASH",
                    "Duplicate Email User",
                    updatedEmail,
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            duplicateEmailUser
                    ),
                    "Duplicate email was not rejected."
            );

            System.out.println(
                    "9. Duplicate email "
                            + "was rejected successfully."
            );

            System.out.println();

            // 10. INVALID EMAIL

            User invalidEmailUser = new User(
                    "invalid_email_" + uniqueSuffix,
                    "INVALID_EMAIL_HASH",
                    "Invalid Email User",
                    "incorrect-email-address",
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            invalidEmailUser
                    ),
                    "Invalid email address was not rejected."
            );

            System.out.println(
                    "10. Invalid email address "
                            + "was rejected successfully."
            );

            System.out.println();

            // 11. INVALID ID

            expectValidationException(
                    () -> userService.getUserById(0),
                    "Invalid user ID was not rejected."
            );

            System.out.println(
                    "11. Invalid user ID "
                            + "was rejected successfully."
            );

            System.out.println();

            // 12. NOT FOUND

            expectNotFoundException(
                    () -> userService.getUserById(
                            Long.MAX_VALUE
                    ),
                    "Missing user did not produce "
                            + "NotFoundException."
            );

            System.out.println(
                    "12. Missing user produced "
                            + "NotFoundException successfully."
            );

            System.out.println();

            // 13. CLEANUP

            cleanupCompleted =
                    deleteTemporaryUser(
                            createdUserId
                    );

            requireCondition(
                    cleanupCompleted,
                    "Temporary user cleanup "
                            + "returned false."
            );

            /*
             * createdUserId is changed earlier, so a final
             * local variable is used inside the lambda.
             */
            final long deletedUserId =
                    createdUserId;

            expectNotFoundException(
                    () -> userService.getUserById(
                            deletedUserId
                    ),
                    "User still exists after cleanup."
            );

            System.out.println(
                    "13. Temporary user "
                            + "was deleted successfully."
            );

            System.out.println(
                    "Deleted user ID: "
                            + deletedUserId
            );

            System.out.println();

            // 14. FINAL COUNT

            int countAfterCleanup =
                    userService
                            .getAllUsers()
                            .size();

            requireCondition(
                    countAfterCleanup
                            == countBeforeCreate,
                    "User count changed after the test. "
                            + "Before: "
                            + countBeforeCreate
                            + ", after: "
                            + countAfterCleanup
            );

            System.out.println(
                    "Users after cleanup: "
                            + countAfterCleanup
            );

            System.out.println();

            System.out.println(
                    "All UserService operations "
                            + "completed successfully."
            );

        } catch (SQLException exception) {

            System.err.println(
                    "UserService cleanup SQL error."
            );

            System.err.println(
                    "SQL error code: "
                            + exception.getErrorCode()
            );

            System.err.println(
                    "SQL state: "
                            + exception.getSQLState()
            );

            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

        } catch (RuntimeException exception) {

            System.err.println(
                    "UserService test failed."
            );

            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

            exception.printStackTrace();

        } finally {

            if (createdUserId != null
                    && !cleanupCompleted) {

                try {
                    boolean removed =
                            deleteTemporaryUser(
                                    createdUserId
                            );

                    if (removed) {
                        System.out.println();

                        System.out.println(
                                "Temporary user was removed "
                                        + "during automatic cleanup."
                        );
                    }

                } catch (SQLException cleanupException) {

                    System.err.println();

                    System.err.println(
                            "Automatic user cleanup failed."
                    );

                    System.err.println(
                            "Temporary user ID: "
                                    + createdUserId
                    );

                    System.err.println(
                            "Reason: "
                                    + cleanupException.getMessage()
                    );
                }
            }
        }
    }

    private static boolean deleteTemporaryUser(long userId)
            throws SQLException {

        try (
                Connection connection =
                        DatabaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(
                                DELETE_TEST_USER_SQL
                        )
        ) {

            statement.setLong(1, userId);

            return statement.executeUpdate() == 1;
        }
    }

    private static void expectValidationException(
            Runnable operation,
            String failureMessage
    ) {

        try {
            operation.run();

        } catch (ValidationException exception) {
            return;
        }

        throw new IllegalStateException(
                failureMessage
        );
    }

    private static void expectNotFoundException(
            Runnable operation,
            String failureMessage
    ) {

        try {
            operation.run();

        } catch (NotFoundException exception) {
            return;
        }

        throw new IllegalStateException(
                failureMessage
        );
    }

    private static void requireCondition(
            boolean condition,
            String message
    ) {

        if (!condition) {
            throw new IllegalStateException(
                    message
            );
        }
    }
}