package com.chebo16.metroit;

import com.chebo16.metroit.exception.NotFoundException;
import com.chebo16.metroit.exception.ValidationException;
import com.chebo16.metroit.model.User;
import com.chebo16.metroit.model.enums.UserRole;
import com.chebo16.metroit.service.UserService;
import com.chebo16.metroit.util.DatabaseConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class UserServiceTest {

    private static final String DELETE_TEST_USER_SQL = """
            DELETE FROM users
            WHERE id = ?
            """;

    public static void main(String[] args) {
        UserService userService =
                new UserService();

        Long createdUserId = null;
        boolean cleanupCompleted = false;

        try {
            System.out.println(
                    "Testing UserService operations..."
            );
            System.out.println();

            List<User> usersBeforeCreate =
                    userService.getAllUsers();

            int countBeforeCreate =
                    usersBeforeCreate.size();

            System.out.println(
                    "1. getAllUsers() completed successfully."
            );
            System.out.println(
                    "Users before create: "
                            + countBeforeCreate
            );
            System.out.println();

            String uniqueSuffix =
                    String.valueOf(System.currentTimeMillis());

            String originalUsername =
                    "service_test_" + uniqueSuffix;

            String originalEmail =
                    "service_test_"
                            + uniqueSuffix
                            + "@example.com";

            String originalPasswordHash =
                    "TEMPORARY_SERVICE_TEST_HASH_"
                            + uniqueSuffix;

            User newUser = new User(
                    "  " + originalUsername + "  ",
                    "  " + originalPasswordHash + "  ",
                    "  Temporary Service Test User  ",
                    "  " + originalEmail + "  ",
                    UserRole.TECHNICIAN
            );

            User createdUser =
                    userService.createUser(newUser);

            createdUserId =
                    createdUser.getId();

            requireCondition(
                    createdUserId != null
                            && createdUserId > 0,
                    "Generated user ID is invalid."
            );

            final long userId =
                    createdUserId;

            requireCondition(
                    originalUsername.equals(
                            createdUser.getUsername()
                    ),
                    "Username was not normalized."
            );

            requireCondition(
                    originalPasswordHash.equals(
                            createdUser.getPasswordHash()
                    ),
                    "Password hash was not normalized."
            );

            requireCondition(
                    "Temporary Service Test User".equals(
                            createdUser.getFullName()
                    ),
                    "Full name was not normalized."
            );

            requireCondition(
                    originalEmail.equals(
                            createdUser.getEmail()
                    ),
                    "Email was not normalized."
            );

            requireCondition(
                    createdUser.getRole()
                            == UserRole.TECHNICIAN,
                    "User role is incorrect."
            );

            requireCondition(
                    createdUser.isActive(),
                    "New user must be active."
            );

            requireCondition(
                    createdUser.getCreatedAt() != null,
                    "createdAt was not generated by MySQL."
            );

            System.out.println(
                    "2. createUser() completed successfully."
            );
            System.out.println(
                    "Generated user ID: " + userId
            );
            System.out.println(
                    "User active status: "
                            + createdUser.isActive()
            );
            System.out.println();

            User loadedUser =
                    userService.getUserById(userId);

            requireCondition(
                    loadedUser.getId() != null
                            && loadedUser.getId() == userId,
                    "getUserById() returned "
                            + "an unexpected user."
            );

            System.out.println(
                    "3. getUserById() "
                            + "completed successfully."
            );
            System.out.println();

            User userByUsername =
                    userService.getUserByUsername(
                            "  " + originalUsername + "  "
                    );

            requireCondition(
                    userByUsername.getId() != null
                            && userByUsername.getId() == userId,
                    "getUserByUsername() returned "
                            + "an unexpected user."
            );

            System.out.println(
                    "4. getUserByUsername() "
                            + "completed successfully."
            );
            System.out.println();

            String updatedUsername =
                    "service_updated_" + uniqueSuffix;

            String updatedEmail =
                    "service_updated_"
                            + uniqueSuffix
                            + "@example.com";

            String updatedPasswordHash =
                    "UPDATED_SERVICE_TEST_HASH_"
                            + uniqueSuffix;

            loadedUser.setUsername(
                    "  " + updatedUsername + "  "
            );

            loadedUser.setPasswordHash(
                    "  " + updatedPasswordHash + "  "
            );

            loadedUser.setFullName(
                    "  Updated Service Test User  "
            );

            loadedUser.setEmail(
                    "  " + updatedEmail + "  "
            );

            loadedUser.setRole(
                    UserRole.ADMIN
            );

            User updatedUser =
                    userService.updateUser(
                            loadedUser
                    );

            requireCondition(
                    updatedUsername.equals(
                            updatedUser.getUsername()
                    ),
                    "Username was not updated."
            );

            requireCondition(
                    updatedPasswordHash.equals(
                            updatedUser.getPasswordHash()
                    ),
                    "Password hash was not updated."
            );

            requireCondition(
                    "Updated Service Test User".equals(
                            updatedUser.getFullName()
                    ),
                    "Full name was not updated."
            );

            requireCondition(
                    updatedEmail.equals(
                            updatedUser.getEmail()
                    ),
                    "Email was not updated."
            );

            requireCondition(
                    updatedUser.getRole()
                            == UserRole.ADMIN,
                    "User role was not updated."
            );

            requireCondition(
                    updatedUser.isActive(),
                    "User active state changed during update."
            );

            User updatedUserByUsername =
                    userService.getUserByUsername(
                            updatedUsername
                    );

            requireCondition(
                    updatedUserByUsername.getId() != null
                            && updatedUserByUsername.getId() == userId,
                    "Updated username could not "
                            + "be resolved correctly."
            );

            System.out.println(
                    "5. updateUser() completed successfully."
            );
            System.out.println();

            User inactiveUser =
                    userService.deactivateUser(userId);

            requireCondition(
                    !inactiveUser.isActive(),
                    "User was not deactivated."
            );

            System.out.println(
                    "6. deactivateUser() "
                            + "completed successfully."
            );
            System.out.println();

            User activeUser =
                    userService.activateUser(userId);

            requireCondition(
                    activeUser.isActive(),
                    "User was not activated."
            );

            System.out.println(
                    "7. activateUser() "
                            + "completed successfully."
            );
            System.out.println();

            User duplicateUsernameUser = new User(
                    updatedUsername,
                    "DUPLICATE_USERNAME_HASH_"
                            + uniqueSuffix,
                    "Duplicate Username User",
                    "unique_"
                            + uniqueSuffix
                            + "@example.com",
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            duplicateUsernameUser
                    ),
                    "Duplicate username was not rejected."
            );

            System.out.println(
                    "8. Duplicate username "
                            + "was rejected successfully."
            );
            System.out.println();

            User duplicateEmailUser = new User(
                    "unique_user_" + uniqueSuffix,
                    "DUPLICATE_EMAIL_HASH_"
                            + uniqueSuffix,
                    "Duplicate Email User",
                    updatedEmail,
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            duplicateEmailUser
                    ),
                    "Duplicate email was not rejected."
            );

            System.out.println(
                    "9. Duplicate email "
                            + "was rejected successfully."
            );
            System.out.println();

            User invalidEmailUser = new User(
                    "invalid_email_" + uniqueSuffix,
                    "INVALID_EMAIL_HASH_"
                            + uniqueSuffix,
                    "Invalid Email User",
                    "incorrect-email-address",
                    UserRole.TECHNICIAN
            );

            expectValidationException(
                    () -> userService.createUser(
                            invalidEmailUser
                    ),
                    "Invalid email address was not rejected."
            );

            System.out.println(
                    "10. Invalid email address "
                            + "was rejected successfully."
            );
            System.out.println();

            expectValidationException(
                    () -> userService.getUserById(0),
                    "Invalid user ID was not rejected."
            );

            System.out.println(
                    "11. Invalid user ID "
                            + "was rejected successfully."
            );
            System.out.println();

            expectNotFoundException(
                    () -> userService.getUserById(
                            Long.MAX_VALUE
                    ),
                    "Missing user did not produce "
                            + "NotFoundException."
            );

            System.out.println(
                    "12. Missing user produced "
                            + "NotFoundException successfully."
            );
            System.out.println();

            cleanupCompleted =
                    deleteTemporaryUser(userId);

            requireCondition(
                    cleanupCompleted,
                    "Temporary user cleanup returned false."
            );

            expectNotFoundException(
                    () -> userService.getUserById(userId),
                    "User still exists after cleanup."
            );

            expectNotFoundException(
                    () -> userService.getUserByUsername(
                            updatedUsername
                    ),
                    "Deleted user is still available "
                            + "by username."
            );

            System.out.println(
                    "13. Temporary user "
                            + "was deleted successfully."
            );
            System.out.println(
                    "Deleted user ID: " + userId
            );
            System.out.println();

            int countAfterCleanup =
                    userService
                            .getAllUsers()
                            .size();

            requireCondition(
                    countAfterCleanup == countBeforeCreate,
                    "User count changed after the test. "
                            + "Before: "
                            + countBeforeCreate
                            + ", after: "
                            + countAfterCleanup
            );

            System.out.println(
                    "Users after cleanup: "
                            + countAfterCleanup
            );
            System.out.println();

            System.out.println(
                    "14. All UserService operations "
                            + "completed successfully."
            );

        } catch (SQLException exception) {
            System.err.println(
                    "UserService cleanup SQL error."
            );
            System.err.println(
                    "SQL error code: "
                            + exception.getErrorCode()
            );
            System.err.println(
                    "SQL state: "
                            + exception.getSQLState()
            );
            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

            throw new IllegalStateException(
                    "UserService test failed "
                            + "because of a database error.",
                    exception
            );

        } catch (RuntimeException exception) {
            System.err.println(
                    "UserService test failed."
            );
            System.err.println(
                    "Reason: "
                            + exception.getMessage()
            );

            throw exception;

        } finally {
            if (createdUserId != null
                    && !cleanupCompleted) {

                try {
                    boolean removed =
                            deleteTemporaryUser(
                                    createdUserId
                            );

                    if (removed) {
                        System.out.println();
                        System.out.println(
                                "Temporary user was removed "
                                        + "during automatic cleanup."
                        );
                    }

                } catch (SQLException cleanupException) {
                    System.err.println();
                    System.err.println(
                            "Automatic user cleanup failed."
                    );
                    System.err.println(
                            "Temporary user ID: "
                                    + createdUserId
                    );
                    System.err.println(
                            "Reason: "
                                    + cleanupException.getMessage()
                    );
                }
            }
        }
    }

    private static boolean deleteTemporaryUser(long userId)
            throws SQLException {

        try (
                Connection connection =
                        DatabaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(
                                DELETE_TEST_USER_SQL
                        )
        ) {
            statement.setLong(1, userId);
            return statement.executeUpdate() == 1;
        }
    }

    private static void expectValidationException(
            Runnable operation,
            String failureMessage
    ) {
        try {
            operation.run();

        } catch (ValidationException exception) {
            return;
        }

        throw new IllegalStateException(failureMessage);
    }

    private static void expectNotFoundException(
            Runnable operation,
            String failureMessage
    ) {
        try {
            operation.run();

        } catch (NotFoundException exception) {
            return;
        }

        throw new IllegalStateException(failureMessage);
    }

    private static void requireCondition(
            boolean condition,
            String message
    ) {
        if (!condition) {
            throw new IllegalStateException(message);
        }
    }
}